<script>
  import { app } from '$lib/state.svelte.js';
  import { normalizeFigmaProps, normalizeWebProps, compareProperties } from '$lib/property-utils.js';

  const figmaNorm = $derived(normalizeFigmaProps(app.figmaProperties));
  const webNorm = $derived(normalizeWebProps(app.webProperties));
  const comparison = $derived(
    figmaNorm || webNorm ? compareProperties(figmaNorm, webNorm) : null
  );

  let expandedCats = $state({});
  let excluded = $state({});

  function toggleCat(key) {
    expandedCats[key] = !expandedCats[key];
  }

  function expandAll() {
    if (!comparison) return;
    for (const cat of comparison.categories) expandedCats[cat.key] = true;
  }

  function collapseAll() {
    if (!comparison) return;
    for (const cat of comparison.categories) expandedCats[cat.key] = false;
  }

  function toggleProp(prop) {
    excluded[prop] = !excluded[prop];
  }

  function toggleCategory(cat) {
    const allExcluded = cat.rows.every(r => excluded[r.prop]);
    for (const r of cat.rows) excluded[r.prop] = !allExcluded;
  }

  function isCatExcluded(cat) {
    return cat.rows.every(r => excluded[r.prop]);
  }

  function isCatPartial(cat) {
    return cat.rows.some(r => excluded[r.prop]) && !isCatExcluded(cat);
  }

  let copyMsg = $state('');

  // Filtered score based on non-excluded properties
  const filtered = $derived.by(() => {
    if (!comparison) return { matched: 0, total: 0, categories: [] };
    let matched = 0, total = 0;
    const categories = comparison.categories.map(cat => {
      const activeRows = cat.rows.filter(r => !excluded[r.prop]);
      const catMatched = activeRows.filter(r => r.match === true).length;
      const catTotal = activeRows.length;
      matched += catMatched;
      total += catTotal;
      return { ...cat, matched: catMatched, total: catTotal, activeRows };
    });
    return { matched, total, categories };
  });

  function buildMarkdown() {
    if (!comparison || !filtered) return '';
    const pct = filtered.total > 0 ? Math.round(filtered.matched / filtered.total * 100) : 0;
    const icon = pct >= 80 ? '🟢' : pct >= 50 ? '🟡' : '🔴';
    let md = `## ${icon} Loupe Inspect — ${pct}% match (${filtered.matched}/${filtered.total})\n\n`;

    for (const cat of comparison.categories) {
      const activeRows = cat.rows.filter(r => !excluded[r.prop]);
      if (activeRows.length === 0) continue;

      const catMatched = activeRows.filter(r => r.match === true).length;
      md += `### ${cat.label} (${catMatched}/${activeRows.length})\n\n`;
      md += `| Property | Figma | Web | Match |\n`;
      md += `|----------|-------|-----|-------|\n`;

      for (const row of activeRows) {
        const status = row.match === true ? '✅' : row.match === false ? '❌' : '➖';
        const f = row.figma ? `\`${row.figma}\`` : '—';
        const w = row.web ? `\`${row.web}\`` : '—';
        md += `| \`${row.prop}\` | ${f} | ${w} | ${status} |\n`;
      }
      md += '\n';
    }

    md += `---\n*Generated by [Loupe](https://github.com/TitaniumCladStudios/loupe)*\n`;
    return md;
  }

  function buildPlainText() {
    if (!comparison || !filtered) return '';
    const pct = filtered.total > 0 ? Math.round(filtered.matched / filtered.total * 100) : 0;
    let txt = `Loupe Inspect — ${pct}% match (${filtered.matched}/${filtered.total})\n`;
    txt += '='.repeat(50) + '\n\n';

    for (const cat of comparison.categories) {
      const activeRows = cat.rows.filter(r => !excluded[r.prop]);
      if (activeRows.length === 0) continue;

      const catMatched = activeRows.filter(r => r.match === true).length;
      txt += `${cat.label} (${catMatched}/${activeRows.length})\n`;
      txt += '-'.repeat(40) + '\n';

      const propW = Math.max(...activeRows.map(r => r.prop.length), 8);
      for (const row of activeRows) {
        const status = row.match === true ? '[OK]' : row.match === false ? '[!!]' : '[--]';
        const f = row.figma || '—';
        const w = row.web || '—';
        txt += `  ${status} ${row.prop.padEnd(propW)}  Figma: ${f}  |  Web: ${w}\n`;
      }
      txt += '\n';
    }
    return txt;
  }

  async function copyMarkdown() {
    await navigator.clipboard.writeText(buildMarkdown());
    copyMsg = 'Markdown copied!';
    setTimeout(() => copyMsg = '', 2000);
  }

  async function copyPlainText() {
    await navigator.clipboard.writeText(buildPlainText());
    copyMsg = 'Plain text copied!';
    setTimeout(() => copyMsg = '', 2000);
  }
</script>

<div class="inspect-tab">
  <p class="tab-desc" title="Compare CSS properties extracted from the Figma frame and the web capture side by side">Compare extracted CSS properties between the Figma design and web implementation. Uncheck properties to exclude them from the similarity score.</p>

  {#if !app.figmaProperties && !app.webProperties}
    <div class="empty-state">
      <div class="icon">
        <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
          <rect x="4" y="8" width="18" height="32" rx="3" stroke="currentColor" stroke-width="2" fill="none"/>
          <rect x="26" y="8" width="18" height="32" rx="3" stroke="currentColor" stroke-width="2" fill="none"/>
          <path d="M14 20h-2m2 4h-2m2 4h-2" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
          <path d="M36 20h-2m2 4h-2m2 4h-2" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
        </svg>
      </div>
      <h2>No properties to compare</h2>
      <p>Capture a Figma frame and a web element first. Properties are extracted automatically during capture.</p>
      <div class="empty-links">
        <button class="btn-link" onclick={() => app.activeTab = 0} title="Go to the Figma tab to capture a frame">Go to Figma</button>
        <button class="btn-link" onclick={() => app.activeTab = 1} title="Go to the Web tab to capture an element">Go to Web</button>
      </div>
    </div>
  {:else if !comparison || comparison.categories.length === 0}
    <div class="empty-state">
      <h2>Waiting for both captures</h2>
      <p>
        {#if !app.figmaProperties}Figma properties not yet received.{/if}
        {#if !app.webProperties}Web properties not yet captured.{/if}
      </p>
      <div class="empty-links">
        {#if !app.figmaProperties}
          <button class="btn-link" onclick={() => app.activeTab = 0}>Go to Figma</button>
        {/if}
        {#if !app.webProperties}
          <button class="btn-link" onclick={() => app.activeTab = 1}>Go to Web</button>
        {/if}
      </div>
    </div>
  {:else}
    <div class="summary-bar">
      <span class="summary-stat">
        <strong>{filtered.matched}</strong> / {filtered.total} properties match
        {#if filtered.total < comparison.totalProps}
          <span class="excluded-note">({comparison.totalProps - filtered.total} excluded)</span>
        {/if}
      </span>
      <div class="summary-actions">
        <button class="btn-toggle" onclick={expandAll} title="Expand all categories">Expand All</button>
        <button class="btn-toggle" onclick={collapseAll} title="Collapse all categories">Collapse All</button>
        <span class="action-divider"></span>
        <button class="btn-toggle btn-export" onclick={copyMarkdown} title="Copy results as Markdown — paste into GitHub PR comments">Copy Markdown</button>
        <button class="btn-toggle btn-export" onclick={copyPlainText} title="Copy results as plain text">Copy Text</button>
        {#if copyMsg}
          <span class="copy-msg">{copyMsg}</span>
        {/if}
      </div>
      {#if filtered.total > 0}
        <span class="summary-pct" class:good={filtered.matched / filtered.total >= 0.8} class:warn={filtered.matched / filtered.total >= 0.5 && filtered.matched / filtered.total < 0.8} class:bad={filtered.matched / filtered.total < 0.5}>
          {Math.round(filtered.matched / filtered.total * 100)}%
        </span>
      {:else}
        <span class="summary-pct bad">—</span>
      {/if}
    </div>

    <div class="categories">
      {#each filtered.categories as cat, ci}
        {@const rawCat = comparison.categories[ci]}
        <div class="category" class:cat-disabled={isCatExcluded(rawCat)}>
          <div class="cat-header">
            <input
              type="checkbox"
              checked={!isCatExcluded(rawCat)}
              indeterminate={isCatPartial(rawCat)}
              onchange={() => toggleCategory(rawCat)}
              title={isCatExcluded(rawCat) ? 'Include all ' + rawCat.label + ' properties in score' : 'Exclude all ' + rawCat.label + ' properties from score'}
              class="cat-check"
            />
            <button class="cat-toggle" onclick={() => toggleCat(rawCat.key)}>
              <span class="cat-arrow">{expandedCats[rawCat.key] ? '▼' : '▶'}</span>
              <span class="cat-label">{rawCat.label}</span>
            </button>
            <span class="cat-summary">
              <span class="cat-count">{cat.matched}/{cat.total}</span>
              {#if cat.total === 0}
                <span class="cat-badge excluded">Excluded</span>
              {:else if cat.matched === cat.total}
                <span class="cat-badge good">All match</span>
              {:else}
                <span class="cat-badge warn">{cat.total - cat.matched} differ</span>
              {/if}
            </span>
          </div>

          {#if expandedCats[rawCat.key]}
            <div class="cat-table">
              <div class="table-header">
                <span class="col-check"></span>
                <span class="col-prop">Property</span>
                <span class="col-val">Figma</span>
                <span class="col-val">Web</span>
                <span class="col-match"></span>
              </div>
              {#each rawCat.rows as row}
                {@const isExcluded = excluded[row.prop]}
                <div
                  class="table-row"
                  class:row-match={!isExcluded && row.match === true}
                  class:row-mismatch={!isExcluded && row.match === false}
                  class:row-unknown={!isExcluded && row.match === null}
                  class:row-excluded={isExcluded}
                >
                  <span class="col-check">
                    <input
                      type="checkbox"
                      checked={!isExcluded}
                      onchange={() => toggleProp(row.prop)}
                      title={isExcluded ? 'Include ' + row.prop + ' in score' : 'Exclude ' + row.prop + ' from score'}
                      class="prop-check"
                    />
                  </span>
                  <span class="col-prop">{row.prop}</span>
                  <span class="col-val" class:empty={!row.figma}>{row.figma ?? '—'}</span>
                  <span class="col-val" class:empty={!row.web}>{row.web ?? '—'}</span>
                  <span class="col-match">
                    {#if isExcluded}
                      <span class="dot gray" title="Excluded from score"></span>
                    {:else if row.match === true}
                      <span class="dot green" title="Values match"></span>
                    {:else if row.match === false}
                      <span class="dot red" title="Values differ"></span>
                    {:else}
                      <span class="dot gray" title="Cannot compare — one side missing or mixed"></span>
                    {/if}
                  </span>
                </div>
              {/each}
            </div>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</div>

<style>
  .inspect-tab {
    display: flex;
    flex-direction: column;
    height: 100%;
    min-height: 400px;
  }

  .tab-desc {
    font-size: 13px;
    color: #6b7280;
    margin: 0 0 12px;
  }

  .empty-state {
    text-align: center;
    color: #6b7280;
    margin: auto;
  }

  .empty-state .icon {
    color: #d1d5db;
    margin-bottom: 16px;
  }

  .empty-state h2 {
    font-size: 18px;
    font-weight: 600;
    color: #374151;
    margin: 0 0 8px;
  }

  .empty-state p {
    font-size: 14px;
    margin: 0 0 16px;
    max-width: 400px;
  }

  .empty-links {
    display: flex;
    gap: 8px;
    justify-content: center;
  }

  .btn-link {
    padding: 8px 16px;
    font-size: 14px;
    font-weight: 500;
    border: 1px solid #6366f1;
    border-radius: 8px;
    background: transparent;
    color: #6366f1;
    cursor: pointer;
  }

  .btn-link:hover {
    background: rgba(99, 102, 241, 0.05);
  }

  /* Summary bar */
  .summary-bar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 12px 16px;
    background: #f3f4f6;
    border-radius: 8px;
    margin-bottom: 12px;
    flex-shrink: 0;
  }

  .summary-stat {
    font-size: 14px;
    color: #374151;
  }

  .excluded-note {
    font-size: 12px;
    color: #9ca3af;
    font-weight: 400;
  }

  .summary-pct {
    font-size: 20px;
    font-weight: 700;
    border-radius: 6px;
    padding: 2px 10px;
  }

  .summary-actions {
    display: flex;
    gap: 4px;
  }

  .btn-toggle {
    padding: 4px 10px;
    font-size: 12px;
    font-weight: 500;
    border: 1px solid #d1d5db;
    border-radius: 6px;
    background: #fff;
    color: #6b7280;
    cursor: pointer;
  }

  .btn-toggle:hover {
    background: #f3f4f6;
    border-color: #9ca3af;
  }

  .btn-export {
    border-color: #6366f1;
    color: #6366f1;
  }

  .btn-export:hover {
    background: rgba(99, 102, 241, 0.06);
    border-color: #4f46e5;
  }

  .action-divider {
    width: 1px;
    height: 18px;
    background: #d1d5db;
    margin: 0 4px;
  }

  .copy-msg {
    font-size: 12px;
    color: #16a34a;
    font-weight: 500;
  }

  .summary-pct.good { color: #16a34a; background: #f0fdf4; }
  .summary-pct.warn { color: #d97706; background: #fffbeb; }
  .summary-pct.bad { color: #dc2626; background: #fef2f2; }

  /* Categories */
  .categories {
    flex: 1;
    overflow: auto;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  .category {
    border: 1px solid #e5e7eb;
    border-radius: 8px;
    overflow: hidden;
  }

  .category.cat-disabled {
    opacity: 0.55;
  }

  .cat-header {
    display: flex;
    align-items: center;
    gap: 8px;
    width: 100%;
    padding: 10px 12px;
    background: #f9fafb;
    font-size: 13px;
    text-align: left;
    border: none;
  }

  .cat-check {
    flex-shrink: 0;
    cursor: pointer;
    accent-color: #6366f1;
    width: 15px;
    height: 15px;
  }

  .cat-toggle {
    display: flex;
    align-items: center;
    gap: 6px;
    flex: 1;
    border: none;
    background: none;
    cursor: pointer;
    padding: 0;
    font-size: 13px;
  }

  .cat-toggle:hover .cat-label {
    text-decoration: underline;
  }

  .cat-arrow {
    color: #9ca3af;
    font-size: 10px;
    width: 14px;
    flex-shrink: 0;
  }

  .cat-label {
    font-weight: 600;
    color: #374151;
  }

  .cat-summary {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .cat-count {
    font-size: 12px;
    color: #9ca3af;
  }

  .cat-badge {
    font-size: 11px;
    font-weight: 600;
    padding: 2px 8px;
    border-radius: 10px;
  }

  .cat-badge.good { background: #dcfce7; color: #16a34a; }
  .cat-badge.warn { background: #fef3c7; color: #d97706; }
  .cat-badge.excluded { background: #e5e7eb; color: #9ca3af; }

  /* Table */
  .cat-table {
    border-top: 1px solid #e5e7eb;
  }

  .table-header {
    display: grid;
    grid-template-columns: 32px 140px 1fr 1fr 32px;
    padding: 6px 12px;
    font-size: 11px;
    font-weight: 600;
    color: #9ca3af;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    background: #fafafa;
  }

  .table-row {
    display: grid;
    grid-template-columns: 32px 140px 1fr 1fr 32px;
    padding: 6px 12px;
    font-size: 13px;
    border-top: 1px solid #f3f4f6;
    align-items: center;
  }

  .table-row:hover {
    background: #fafafa;
  }

  .table-row.row-mismatch {
    background: #fef2f2;
  }

  .table-row.row-mismatch:hover {
    background: #fee2e2;
  }

  .table-row.row-excluded {
    opacity: 0.45;
  }

  .table-row.row-excluded:hover {
    opacity: 0.65;
  }

  .col-check {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .prop-check {
    cursor: pointer;
    accent-color: #6366f1;
    width: 14px;
    height: 14px;
  }

  .col-prop {
    font-weight: 500;
    color: #374151;
    font-family: 'SF Mono', Monaco, Consolas, monospace;
    font-size: 12px;
  }

  .col-val {
    color: #4b5563;
    font-family: 'SF Mono', Monaco, Consolas, monospace;
    font-size: 12px;
    word-break: break-all;
    padding-right: 8px;
  }

  .col-val.empty {
    color: #d1d5db;
    font-style: italic;
  }

  .col-match {
    display: flex;
    justify-content: center;
  }

  .dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    display: inline-block;
  }

  .dot.green { background: #22c55e; }
  .dot.red { background: #ef4444; }
  .dot.gray { background: #d1d5db; }

  @media (prefers-color-scheme: dark) {
    .tab-desc { color: #9ca3af; }
    .empty-state h2 { color: #e5e7eb; }
    .empty-state .icon { color: #4b5563; }
    .btn-link { border-color: #818cf8; color: #818cf8; }
    .summary-bar { background: #1f2937; }
    .btn-toggle { background: #374151; border-color: #4b5563; color: #9ca3af; }
    .btn-toggle:hover { background: #4b5563; }
    .btn-export { border-color: #818cf8; color: #818cf8; }
    .btn-export:hover { background: rgba(129, 140, 248, 0.1); }
    .action-divider { background: #4b5563; }
    .copy-msg { color: #4ade80; }
    .summary-stat { color: #d1d5db; }
    .excluded-note { color: #6b7280; }
    .summary-pct.good { color: #4ade80; background: #052e16; }
    .summary-pct.warn { color: #fbbf24; background: #422006; }
    .summary-pct.bad { color: #f87171; background: #450a0a; }
    .category { border-color: #374151; }
    .cat-header { background: #111827; }
    .cat-toggle:hover .cat-label { color: #c7d2fe; }
    .cat-label { color: #e5e7eb; }
    .cat-badge.good { background: #052e16; color: #4ade80; }
    .cat-badge.warn { background: #422006; color: #fbbf24; }
    .cat-badge.excluded { background: #374151; color: #6b7280; }
    .cat-table { border-color: #374151; }
    .table-header { background: #111827; color: #6b7280; }
    .table-row { border-color: #1f2937; }
    .table-row:hover { background: #111827; }
    .table-row.row-mismatch { background: #450a0a; }
    .table-row.row-mismatch:hover { background: #7f1d1d; }
    .col-prop { color: #d1d5db; }
    .col-val { color: #9ca3af; }
    .col-val.empty { color: #4b5563; }
  }
</style>
